
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    API_KEY: 'd6ac7457-a1ca-4710-8cff-47991b9ffcc2'
  };
